version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:12.18.3
        working_directory: ~/src
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run:
                  command: npm install
            - save_cache:
                  key: v1-npm-deps-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run:
                  command: npm run build
            - run:
                  command: npm run test
            - run: |
                  if [ "$CIRCLE_BRANCH" = "master" ]; then
                      ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
                  fi
